#!/usr/bin/env bash
set -eEuo pipefail

# shellcheck disable=SC2016

(
	sed ':a;N;$!ba;s/\\\n/<C2DNEWLINE>/g'
) | (
	args=(
		perl

		-pe 's|#include(\s*)<(.*)\.h>|import\1core.stdc.\2;|g;'

		# empty macro
		-pe 's|#define(\s*)(\S*)\(([^()]*)\)(\s+/[/*].*)?$|void\1\2(\3)(\3)\4 \{ pragma(inline\, true); }\5|g;'

		# function macro
	#	-pe 's|#define(\s*)(\S*)\(([^()]*)\)(\s*)(.+?)(\s+/[/*].*)?$|auto\1\2(\3)(\3)\4\{ pragma(inline\, true); return \5; }\6|g;'
		-pe 's/#define(\s*)(\S*)\(([^()]*)\)(\s*)(.+?)(\s+\/[\/*].*)?$/
			$spc4 = $4;
			$expr = $5;
			$tail = $6;
			"auto $1$2($3)(" . (
				  $3 =~ s|(\w+)|\1 \1|rg
			) . ")$spc4\{ pragma(inline, true); return $expr; }$tail"
		/ge;'

		# definition
		-pe 's|#(\s*)define(\s*)(\S+)(\s+)([a-zA-Z_]\w+?)(\s+/[/*].*)?$|\1alias\2\3\4= \5;\6|g;'
		-pe 's|#(\s*)define(\s*)(\S+)(\s+)(.+?)(\s+/[/*].*)?$|\1enum\2\3\4= \5;\6|g;'

		-pe 's|#if\s*1|version (all) {|g;'
		-pe 's|#if\s*0|version (none) {|g;'

		-pe 's|#if(\s+)defined(\s*)\((\S*)\)|version\1\2(\3) {|g;'
		-pe 's|#elif(\s+)defined(\s*)\((\S*)\)|} else version\1\2(\3) {|g;'
		-pe 's|#ifdef(\s*)(\S*)|version\1(\2) {|g;'
		-pe 's|#ifndef(\s*)(\S*)|version\1(\2) {} else {|g;'

		# -pe 's|#if\s+defined(\s*)\((\S*)\)|static if\1(is(typeof(\2))) {|g;'
		# -pe 's|#elif\s+defined(\s*)\((\S*)\)|} else static if\1(is(typeof(\2))) {|g;'
		# -pe 's|#ifdef(\s*)(\S*)|static if\1(is(typeof(\2))) {|g;'
		# -pe 's|#ifndef(\s*)(\S*)|static if\1(!is(typeof(\2))) {|g;'

		-pe 's|#if(\s+)(.*)|static if\1(\2) {|g;'
		-pe 's|#elif(\s+)(.*)|} else static if\1(\2) {|g;'
		-pe 's|#else\b|} else {|g;'
		-pe 's|#end\b|}|g;'
		-pe 's|#endif|}|g;'

		-pe 's|#undef\b|//#undef|g;'
		-pe 's|\bunsigned char\b|ubyte|g;'
		-pe 's|\bunsigned short\b|ushort|g;'
		-pe 's|\bunsigned int\b|uint|g;'
		-pe 's|\bunsigned long\b|c_ulong|g;'
		-pe 's|\bunsigned\b|uint|g;'
		-pe 's|\blong\b|c_long|g;'
		-pe 's|typedef(\s+)(.+?)(\s*)\b(\w*)(\s*);|alias\1\4\3 = \2\5;|g;'

		-pe 's|const\s+([^ ()*,]+)|const(\1)|g;'

		-pe 's|\b0([0-9])|octal!\1|g;'
		-pe 's|\bNULL\b|null|g;'

		-pe 's|\(void\);|();|g;'

		-pe 's|->|.|g;'
	) ; "${args[@]}"
) | (
	sed 's/<C2DNEWLINE>/\n/g'
)
