#!/bin/bash
set -eu

# Hook for preparing a commit message template based on which files
# are modified. Install by symlinking .git/hooks/prepare-commit-msg to
# this script. Invokes git-status-to-commit-msg to do the real work.

# Recently, GIT_DIR is no longer set. Try to detect it instead.

if [[ ! -v GIT_DIR ]]
then
	if [[ -d .git ]]
	then
		GIT_DIR=.git
	fi
fi

# Remove our template from git-gui

# We only want to edit the template for NEW commits.

if [[ $# -gt 1 ]]
then
	exit 0
fi

test -f "$GIT_DIR"/GITGUI_MSG && ! grep -vqE '^[^ ]+:$' "$GIT_DIR"/GITGUI_MSG && rm "$GIT_DIR"/GITGUI_MSG

# Update commit message file

old_message=$(cat "$1")
(
	git status --porcelain | "$(dirname "$(realpath "$0")")"/git-status-to-commit-msg
	printf '\n'
	grep -v '^[^ ]+: ?$' <<< "$old_message"
) > "$1"
