#!/bin/bash
set -eux

# Undo the effects of the gpu-windows script and give back the GPU and
# other devices to the Linux host.

WIN_VM=win-vfio

#DM=sddm.service
DM=nodm.service

# Remove devices from Windows
#ssh 192.168.0.18 devcon remove '"@PCI\VEN_10DE&DEV_1005&SUBSYS_84511043&REV_A1\3&13C0B0C5&0&78"'
#ssh 192.168.0.18 devcon remove '"@HDAUDIO\FUNC_01&VEN_10DE&DEV_0044&SUBSYS_10438451&REV_1001\4&124E27CE&1&0001"'

#ssh 192.168.0.18 devcon remove '"@PCI\VEN_10DE&DEV_1005&SUBSYS_84511043&REV_A1\*"'
#ssh 192.168.0.18 devcon remove '"@HDAUDIO\FUNC_01&VEN_10DE&DEV_0044&SUBSYS_10438451&REV_1001\*"'

if [[ "$(sudo virsh list --all | awk -v "name=$WIN_VM" '($2==name) {print $3}')" == running ]]
then
	# Detach from virsh
	for D in gpu gpu-audio mouse keyboard
	do
		sudo virsh detach-device $WIN_VM ~/work/misc/hostdev/$D.xml || true
	done
fi

# Unbind devices from VFIO
echo 10de 1005 | sudo tee /sys/bus/pci/drivers/vfio-pci/remove_id
echo 0000:05:00.0 | sudo tee /sys/bus/pci/drivers/vfio-pci/unbind
#echo 10de 0e1a | sudo tee /sys/bus/pci/drivers/vfio-pci/new_id

sudo modprobe nvidia
sudo modprobe nvidia_modeset

echo 10de 1005 | sudo tee /sys/bus/pci/drivers/nvidia/new_id

echo efi-framebuffer.0 | sudo tee /sys/bus/platform/drivers/efi-framebuffer/bind

echo 1 | sudo tee /sys/class/vtconsole/vtcon1/bind

sudo systemctl start "$DM"
