#!/bin/bash

# Locate helper for helm-locate, helm-for-files, etc.
# Filters unnecessary junk and prioritizes files from more likely
# locations.

function run() {
	local tmpfile=/tmp/locate-emacs.$$
	unbuffer plocate "$@" \
		| grep --line-buffered -vFf \
			   ~/work/misc/locate-emacs-exclusions.txt \
		| tee "$tmpfile" \
		| grep --line-buffered -vFf \
			   ~/work/misc/locate-emacs-lowprio.txt

	grep --line-buffered -Ff \
		 ~/work/misc/locate-emacs-lowprio.txt \
		 < "$tmpfile"

	rm -f "$tmpfile"
}

if [[ -e ~/.stream-mode/enabled ]]
then
	run "$@" | grep --line-buffered -Ff ~/work/misc/public-dirs.txt
else
	run "$@"
fi
