#!/bin/bash

function run() {
	local tmpfile=/tmp/locate-emacs.$PID
	unbuffer locate --regex "$@" \
		| grep --line-buffered -vFf \
			   ~/work/misc/locate-emacs-exclusions.txt \
		| tee "$tmpfile" \
		| grep --line-buffered -vFf \
			   ~/work/misc/locate-emacs-lowprio.txt

	grep --line-buffered -Ff \
		 ~/work/misc/locate-emacs-lowprio.txt \
		 < "$tmpfile"

	rm -f "$tmpfile"
}

if [[ -e ~/.stream-mode/enabled ]]
then
	run "$@" | grep --line-buffered -Ff ~/work/misc/public-dirs.txt
else
	run "$@"
fi
