name: test
on: [ push, pull_request ]

jobs:
  test:
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        dc: [ dmd-2.100.0 ]
        arch: [ x86_64 ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v27
      - run: nix-build --show-trace -A programs
      - run: nix-build --show-trace -A tests
      - run: nix --extra-experimental-features 'nix-command flakes' build .
      - run: nix --extra-experimental-features 'nix-command flakes' flake check
      - run: nix --extra-experimental-features 'nix-command flakes' run -- .#greplace --help
