name: test
on: [ push, pull_request ]

jobs:
  test:
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        dc: [ dmd-2.100.0 ]
        arch: [ x86_64 ]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install D compiler
        uses: dlang-community/setup-dlang@1ccbc70a0eff7f264857b53c562aa45fd7f1e479
        with:
          compiler: ${{ matrix.dc }}

      - run: ./ci
